- README
Needed after 4e26d04d642cfacc659bea2e92379d1cd3cd5ea5
> Add libtool to build dependencies

- src/process_request.cpp
- test/empty.testcore/cors_preflight.case
- test/test_core.cpp
Fixes #102.
@woodpeck - how does that look?
> Add headers to cors preflight

- .travis.yml
Lets be consistent about how we install packages for travis...
> Install all packages using apt addon

- src/oauth.cpp
- test/test_oauth.cpp
This (along with the corresponding rails commit) will allow us to expire old nonces rather than having to keep them around forever.
> Reject oauth nonces over a day old

- include/cgimap/data_selection.hpp
- src/backend/apidb/writeable_pgsql_selection.cpp
- src/data_selection.cpp
- test/test_apidb_backend.cpp
- test/test_apidb_backend.sql
Draft PR for #123 
I have fixed the query only for write_node method, will fix other methods after initial review
Thanks
> Fix per-node separate tag query

- src/backend/apidb/writeable_pgsql_selection.cpp
Used `LEFT JOIN LATERAL` for combining multiple joins to avoid cross product between tables.
Please review.
Thanks
> Fixes per element queries

- .travis.yml
- src/backend/apidb/readonly_pgsql_selection.cpp
- src/backend/apidb/writeable_pgsql_selection.cpp
- src/backend/pgsnapshot/snapshot_selection.cpp
> Add check Postgres version during connection setup

- src/backend/apidb/readonly_pgsql_selection.cpp
- src/backend/apidb/writeable_pgsql_selection.cpp
- src/backend/pgsnapshot/snapshot_selection.cpp
> Add default_transaction_read_only 

- src/json_formatter.cpp
- src/xml_formatter.cpp
- test/changesets.testcore/read.case
- test/changesets.testcore/read_discussion.case
- test/changesets.testcore/read_nonpublic.case
- test/changesets.testcore/read_open.case
> Include num_changes in changeset xml & json response

- src/process_request.cpp
Fixes current measurement, which is accurate to a second only.
> High precision time measurement

- include/cgimap/http.hpp
- include/cgimap/zlib.hpp
- src/fcgi_request.cpp
- src/http.cpp
- src/process_request.cpp
- src/request_helpers.cpp
- src/zlib.cpp
> Input decompression

- src/backend/apidb/writeable_pgsql_selection.cpp
- test/test_apidb_backend_historic.cpp
> Fix history api returns wrong/duplicate tag data for ways

- test/test_apidb_backend_changeset_uploads.cpp
There's always more unit tests to be added. This pull requests improves history table coverage for all operations and objects.
> Adding more unit tests for history tables

- src/process_request.cpp
> Reorder WWW-Authenticate headers to work around non-compliant clients

- src/backend/apidb/readonly_pgsql_selection.cpp
- src/backend/apidb/writeable_pgsql_selection.cpp
- src/basicauth.cpp
- test/test_apidb_backend_changeset_uploads.cpp
- test/test_basicauth.cpp
- test/test_database.cpp
Keeps authentication is line with user.rb, authenticate method
See #189
> Basic auth should also consider user email and lower case variants

- src/process_request.cpp
> Remove OAuth WWW-Authenticate header for better rails compatibility

- src/backend/apidb/changeset_upload/relation_updater.cpp
- src/backend/apidb/changeset_upload/way_updater.cpp
- test/test_apidb_backend_changeset_uploads.cpp
> Fix 412 Precondition Failed when trying to upload old version of a way

- src/backend/apidb/common_pgsql_selection.cpp
- src/backend/apidb/readonly_pgsql_selection.cpp
> Fix compilation issues for libpqxx 6.x

- Vagrantfile
- scripts/provision.sh
> Update Vagrantfile to use bionic

- src/json_formatter.cpp
> JSON: omit empty way nodes array

- include/cgimap/mime_types.hpp
- src/choose_formatter.cpp
- src/json_formatter.cpp
- src/mime_types.cpp
- src/osm_responder.cpp
- src/routes.cpp
- test/json.testcore/map_all.case
- test/json.testcore/node_1.case
- test/json.testcore/node_2.case
- test/test_core.cpp
* Use content-type application/json according to RFC 4627
* Disable pretty printing (alignment w/ Rails port)
> JSON fixes

- include/cgimap/backend/apidb/changeset_upload/relation_updater.hpp
- src/backend/apidb/changeset_upload/relation_updater.cpp
- test/test_apidb_backend_changeset_uploads.cpp
> Fix: revert deleted master/child relations

- include/cgimap/backend/apidb/changeset_upload/relation_updater.hpp
- src/backend/apidb/changeset_upload/relation_updater.cpp
- test/test_apidb_backend_changeset_uploads.cpp
> Fix relations referencing deleted elements

- .travis.yml
- include/cgimap/backend/apidb/transaction_manager.hpp
- src/backend/apidb/changeset.cpp
- src/backend/apidb/changeset_upload/changeset_updater.cpp
- src/backend/apidb/oauth_store.cpp
- src/backend/apidb/transaction_manager.cpp
- src/osm_diffresult_responder.cpp
- test/test_apidb_backend_oauth.cpp
- test/test_basicauth.cpp
- test/test_database.cpp
- test/test_formatter.cpp
Thanks to previous work in #200, unit tests passed without changes.
In this pull request, remaining deprecation and compiler warnings will be fixed.
> Ubuntu 20.04 (Focal) adjustments

- include/cgimap/api06/changeset_upload/way.hpp
- include/cgimap/backend/apidb/apidb.hpp
- include/cgimap/backend/staticxml/staticxml.hpp
- include/cgimap/options.hpp
- include/cgimap/util.hpp
- openstreetmap-cgimap.1
- src/Makefile.am
- src/api06/map_handler.cpp
- src/api07/map_handler.cpp
- src/backend/apidb/apidb.cpp
- src/backend/apidb/changeset_upload/changeset_updater.cpp
- src/backend/apidb/changeset_upload/node_updater.cpp
- src/backend/apidb/changeset_upload/way_updater.cpp
- src/backend/apidb/common_pgsql_selection.cpp
- src/backend/apidb/readonly_pgsql_selection.cpp
- src/fcgi_request.cpp
- src/http.cpp
- src/main.cpp
- src/options.cpp
- test/test_apidb_backend_changeset_uploads.cpp
- test/test_parse_osmchange_input.cpp
Revised implementation for #222 
Closes #222, closes #84.
> Make MAX_NODES and MAX_AREA values configurable (2)

- README
- scripts/cgimap.service
( Markdown rendering is shown here: https://github.com/mmd-osm/openstreetmap-cgimap/tree/patch/readme )
> Updated README, example systemd service

- Makefile.am
- include/cgimap/backend/apidb/oauth_store.hpp
- include/cgimap/oauth.hpp
- include/cgimap/oauth2.hpp
- include/cgimap/process_request.hpp
- src/Makefile.am
- src/backend/apidb/oauth_store.cpp
- src/oauth.cpp
- src/oauth2.cpp
- src/process_request.cpp
- test/structure.sql
- test/test_apidb_backend_oauth2.cpp
- test/test_core.cpp
- test/test_oauth.cpp
- test/test_oauth2.cpp
> Adding OAuth2 support

- src/backend/apidb/changeset_upload/node_updater.cpp
- src/backend/apidb/changeset_upload/relation_updater.cpp
- src/backend/apidb/changeset_upload/way_updater.cpp
Defect found by static source code scan (Coverity)
> Fix copy&paste error

- src/backend/apidb/readonly_pgsql_selection.cpp
Fixes https://github.com/zerebubuth/openstreetmap-cgimap/issues/281
> Fix vector reserve in pqsql select for historic n/w/r

- .github/workflows/alt.yml
- Dockerfile_trixie
- include/cgimap/backend/apidb/pgsql_update.hpp
- include/cgimap/backend/apidb/pqxx_string_traits.hpp
- include/cgimap/backend/apidb/readonly_pgsql_selection.hpp
- include/cgimap/backend/apidb/transaction_manager.hpp
- src/backend/apidb/oauth_store.cpp
- src/backend/apidb/pgsql_update.cpp
- src/backend/apidb/readonly_pgsql_selection.cpp
- src/backend/apidb/transaction_manager.cpp
- src/backend/staticxml/staticxml.cpp
- src/main.cpp
- test/test_basicauth.cpp
- test/test_database.cpp
- test/test_oauth2.cpp
> Adjustments for changes in underlying libpqxx 7.x.x library version

- test/test_apidb_backend_changeset_uploads.cpp
- test/test_parse_changeset_input.cpp
- test/test_request.cpp
Also added a few forgotten `throw` in unit test checks (no impact on non unit test code).
> Added testcase for compressed changeset uploads

- Dockerfile_bookworm
- Dockerfile_trixie
- src/Makefile.am
- test/test_apidb_backend_changeset_downloads.cpp
- test/test_apidb_backend_changesets.cpp
- test/test_apidb_backend_historic.cpp
- test/test_apidb_backend_nodes.cpp
- test/test_parse_changeset_input.cpp
- test/test_request.cpp
* Slim docker images for Debian
* Unit tests, continue Catch2 migration
> Various minor cleanups

- src/main.cpp
Install signal handlers for daemon and non-daemon mode + split into separate function
> Install signal handlers for daemon and non-daemon mode

- include/cgimap/backend/apidb/common_pgsql_selection.hpp
- src/backend/apidb/common_pgsql_selection.cpp
std::string append is ~2-3 times faster than string streams
https://quick-bench.com/q/JLjFJX98msn1zUpsn0I6a0voUqc
> Use std::string / std::string_view for psql_array_to_vector

- src/api06/handler_utils.cpp
> Fix test_parse_id_list failure on ARM64

- src/Makefile.am
- test/test_apidb_backend_changeset_uploads.cpp
- test/test_request.cpp
Baseline migration, remaining functions will be migrated in subsequent commits.
> Catch2 migration: test_apidb_backend_changeset_uploads

- test/test_apidb_backend_changeset_uploads.cpp
> Changeset upload: validate error message texts

- test/test_apidb_backend_changeset_uploads.cpp
Adds diffResult XML response checks in unit tests
> changeset_upload: validate diffResult XML response

- .gitignore
\+ emacs temporary backup files
> Add code coverage / profiling files to gitignore

- .github/workflows/codeql.yml
- .github/workflows/docker_2004.yml
- .github/workflows/docker_2204.yml
- .github/workflows/docker_bookworm.yml
- .github/workflows/docker_trixie.yml
Resolve some gh deprecation warnings
> Update Github Actions

- include/cgimap/handler.hpp
- include/cgimap/mime_types.hpp
- include/cgimap/output_formatter.hpp
- src/api06/changeset_close_handler.cpp
- src/api06/changeset_create_handler.cpp
- src/api06/changeset_update_handler.cpp
- src/api06/changeset_upload_handler.cpp
- src/backend/apidb/common_pgsql_selection.cpp
- src/backend/staticxml/staticxml.cpp
- src/choose_formatter.cpp
- src/json_formatter.cpp
- src/mime_types.cpp
- src/osm_current_responder.cpp
- src/osm_diffresult_responder.cpp
- src/osm_responder.cpp
- src/osmchange_responder.cpp
- src/routes.cpp
- src/text_formatter.cpp
- src/text_responder.cpp
- src/xml_formatter.cpp
- test/test_apidb_backend_changeset_downloads.cpp
- test/test_apidb_backend_changeset_uploads.cpp
- test/test_apidb_backend_historic.cpp
- test/test_formatter.cpp
... for improved type safety
Also moved duplicate element_type_name function to common header file.
> Change some enums to enum class

- include/cgimap/fcgi_request.hpp
- src/fcgi_request.cpp
- src/http.cpp
- src/oauth2.cpp
* Reuse buffers in fcgi_request
* Avoid recompiling regular expressions
> Small performance improvements

- README
Fixes https://github.com/zerebubuth/openstreetmap-cgimap/issues/393
> Update apache fcgi module link in readme

- docker/debian/Dockerfile_bookworm
- docker/debian/Dockerfile_trixie
- docker/ubuntu/Dockerfile
- docker/ubuntu/Dockerfile2204
As reported here: https://github.com/zerebubuth/openstreetmap-cgimap/issues/394#issuecomment-2067105448
> Added missing brotli libs in Dockerfile stage 2

- test/structure.sql
- test/test_apidb_backend_changeset_downloads.cpp
- test/test_apidb_backend_historic.cpp
- test/test_database.cpp
\+ Add required non-null redaction description field in test data
\+ Set UTF8 server encoding for temporary test databases (required for unicode normalization)
Requires https://github.com/zerebubuth/openstreetmap-cgimap/pull/405
> Sync test db schema with upstream openstreetmap-website

- test/test_apidb_backend_changeset_uploads.cpp
Somehow this test was commented when basic auth was removed. This PR brings it back.
Also removes basic auth test cases which are no longer relevant.
> Unit test: user in status pending cannot upload changesets

- .github/workflows/docker_trixie.yml
Debian Trixie packaging issues have been fixed, build works again
> Reenable gh actions docker trixie build

- include/cgimap/backend/apidb/transaction_manager.hpp
- src/backend/apidb/changeset_upload/node_updater.cpp
- src/backend/apidb/changeset_upload/relation_updater.cpp
- src/backend/apidb/changeset_upload/way_updater.cpp
Closes #408 ... there's also some further discussion in that issue regarding pending performance testing.
In scope for this PR:
*  ApiDB_Node_Updater: insert_new_current_node_tags
*  ApiDB_Way_Updater:  insert_new_current_way_tags, insert_new_current_way_nodes
*  ApiDB_Relation_Updater: insert_new_current_relation_tags,  insert_new_current_relation_members
> Enable libpqxx stream_to for selected tables

- include/cgimap/api06/changeset_handler.hpp
- include/cgimap/json_formatter.hpp
- include/cgimap/osm_changeset_responder.hpp
- include/cgimap/output_formatter.hpp
- include/cgimap/text_formatter.hpp
- include/cgimap/xml_formatter.hpp
- src/CMakeLists.txt
- src/api06/changeset_handler.cpp
- src/json_formatter.cpp
- src/osm_changeset_responder.cpp
- src/osm_current_responder.cpp
- src/osmchange_responder.cpp
- src/text_formatter.cpp
- src/xml_formatter.cpp
- test/changesets.testcore/read_discussion_json.case
- test/changesets.testcore/read_discussion_multiple_json.case
- test/changesets.testcore/read_json.case
- test/test_formatter.cpp
- test/test_formatter.hpp
See https://github.com/openstreetmap/openstreetmap-website/issues/5047 for details
> Rework changeset json output according to Rails implementation

- include/cgimap/util.hpp
- src/backend/apidb/changeset_upload/node_updater.cpp
- src/backend/apidb/changeset_upload/relation_updater.cpp
- src/backend/apidb/changeset_upload/way_updater.cpp
> Small cleanups

- src/oauth2.cpp
Based on changes in 07d3ac22d406fe809a8dd4e57a07f81364f10e54
> Simplified is_valid_bearer_token_char

- src/backend/apidb/pgsql_update.cpp
> Refactor connopt to proper function

- CMakeLists.txt
- debian/changelog
- debian/control
See https://github.com/zerebubuth/openstreetmap-cgimap/pull/449#issuecomment-2308776646
> Replace old openstreetmap-cgimap-bin Debian package

- include/cgimap/backend/apidb/changeset_upload/node_updater.hpp
- include/cgimap/backend/apidb/changeset_upload/relation_updater.hpp
- include/cgimap/backend/apidb/changeset_upload/way_updater.hpp
- include/cgimap/backend/apidb/transaction_manager.hpp
- include/cgimap/util.hpp
- src/backend/apidb/changeset_upload/node_updater.cpp
- src/backend/apidb/changeset_upload/relation_updater.cpp
- src/backend/apidb/changeset_upload/way_updater.cpp
- src/backend/apidb/pgsql_update.cpp
- src/backend/apidb/readonly_pgsql_selection.cpp
- src/backend/apidb/transaction_manager.cpp
See single commits for details
> Diff upload: minor improvements

- include/cgimap/api06/changeset_upload/relation.hpp
- include/cgimap/util.hpp
- src/api06/handler_utils.cpp
- src/bbox.cpp
- src/http.cpp
- src/process_request.cpp
- src/routes.cpp
- test/test_parse_id_list.cpp
In scope for this change:
* boost::iequals
* boost spirit parser for id/version
See commits for details
> Reduce boost footprint

- test/CMakeLists.txt
- test/test_utils.cpp
Test for is_comma_separated_string is part of #474 and not yet merged
Edit: we're testing to_string instead now.
> Util unit tests from #474

- test/test_core.cpp
* Merge XML / JSON versions of check_recursive_tree into single function. They were almost identical.
* Check XML attributes: report all attributes that are present in either expected or actual payload
* check extra/missing entries move to own functions
> test_core: code improvements

- debian/rules
> deb package: run pg_virtualenv only once for all test cases

- test/CMakeLists.txt
- test/test_core_check.cpp
- test/test_core_helper.hpp
- test/test_types.hpp
Unit testing the unit test framework...
> Adding unit tests for test_core_helper

- include/cgimap/http.hpp
- src/http.cpp
We let the compiler do the work...
> http exceptions as template

- include/cgimap/backend/apidb/pgsql_update.hpp
- include/cgimap/backend/apidb/transaction_manager.hpp
- include/cgimap/data_update.hpp
- include/cgimap/http.hpp
- src/backend/apidb/pgsql_update.cpp
- test/test_core_check.cpp
- test/test_core_helper.cpp
- test/test_core_helper.hpp
- test/test_empty_selection.hpp
- test/test_oauth2.cpp
- test/test_types.hpp
> Minor cleanups

- include/cgimap/backend/apidb/utils.hpp
- src/backend/apidb/pgsql_update.cpp
- src/backend/apidb/readonly_pgsql_selection.cpp
- src/backend/apidb/utils.cpp
- test/test_apidb_backend_nodes.cpp
Old bug that has been around since 2013 or earlier.
> Escape values in postgresql connection string

- CMakeLists.txt
- contrib/CMakeLists.txt
- include/cgimap/output_formatter.hpp
Fixes https://github.com/zerebubuth/openstreetmap-cgimap/issues/508
> Compile time customizable COPYRIGHT, ATTRIBUTION and LICENSE strings

- test/test_apidb_importer.cpp
Backfilling code is only used for unit tests. SQL statement now matches https://github.com/openstreetmap/openstreetmap-website/pull/6347
> Fix enhanced changeset stats backfilling
