README

Curiously it fails with a misleading error (configure: error: Could not link against boost_date_time-mt !) but that's not too important.

Add libboost-filesystem-dev to dependencies

---

.travis.yml

This (which makes travis jobs run on the newer container based infrastructure) was waiting on them whitelisting one of the packages, which is now done.

Switch travis to container mode

---

src/main.cpp

added the "port" option for daemon mode in `get_options` function.

fixed a bug that in daemon mode, legacy "port" option fallback not recognized.

---

Makefile.am
include/cgimap/api06/node_version_handler.hpp
include/cgimap/api06/relation_version_handler.hpp
include/cgimap/api06/way_version_handler.hpp
src/Makefile.am
src/api06/node_version_handler.cpp
src/api06/relation_version_handler.cpp
src/api06/way_version_handler.cpp
src/routes.cpp
test/node.testcore/node_version.case
test/node.testcore/node_version_deleted.case
test/node.testcore/node_version_missing.case
test/relation.testcore/relation_version.case
test/relation.testcore/relation_version_deleted.case
test/relation.testcore/relation_version_missing.case
test/way.testcore/way_version.case
test/way.testcore/way_version_deleted.case
test/way.testcore/way_version_missing.case

This pull requests adds support (and tests) for requests of the form /.../{node|way|relation}/[id]/[version]

Add API calls for specific historic versions of objects

---

README

Added instructions for installing and running cgimap with lighttpd

Add documentation about lighttpd usage

---

lighttpd.conf

Fixes #52, routes the unknown call to the cgimap to display a verbose message. I haven't included the code to return an error message as it is being handled in #125.

Add unknown route handler in lighttpd configuration

---

Makefile.am
lighttpd.conf
src/routes.cpp
test/routes.testcore/data.osm
test/routes.testcore/way_id_extra.case

Fixes #52. 
Solved it by checking if the request path has been matched/iterated completely. I think we can use the existing router with this fix for now until we have a new router.
Should I add the test cases as shown in 52-unknown-api-calls?
Let me know if I have to fix my code style/syntax.
Thanks!

Fix reject unknown api calls with 404

---

Makefile.am
src/api06/changeset_handler.cpp
src/api06/node_handler.cpp
src/api06/node_ways_handler.cpp
src/api06/relation_full_handler.cpp
src/api06/relation_handler.cpp
src/api06/way_full_handler.cpp
src/api06/way_handler.cpp
src/process_request.cpp
src/routes.cpp
test/map.testcore/bad_bbox_001.case
test/map.testcore/bad_bbox_002.case
test/map.testcore/bad_bbox_003.case
test/map.testcore/bad_bbox_004.case
test/map.testcore/bad_bbox_005.case
test/map.testcore/bad_bbox_006.case
test/map.testcore/bad_bbox_007.case
test/map.testcore/bad_bbox_008.case
test/message.testcore/data.osm
test/message.testcore/map_400.case
test/message.testcore/map_400_xml.case
test/message.testcore/node_404.case
test/message.testcore/node_404_xml.case
test/test_core.cpp

Thanks to @mmd-osm for pointing this out in #124.
It looks like this sort of worked as of #83, although returning HTML rather than plain text as the Rails code does. That was sort of fixed in 1d0e06f2bdcbb5efc5ec7908e79d5d4e65fd139f to match the behaviour of _most_ of the Rails errors: which is to print a blank string as the error. Unfortunately, the side effect was disabling display in the body of all messages.
This branch tries to fix this, first by printing the error messages in the response body and secondly by providing error messages for all the various `not_found` cases.
This is a departure from strict compatibility with the Rails code. However, most of the `not_found` messages that the Rails code generates are translations from `ActiveRecord::RecordNotFound`. If I remember …

Fix HTTP error messages

---

src/request_helpers.cpp

Using lighttpd/1.4.39
The query_string env is empty even when URI has a query, this PR fixes it. 
Thanks!

Fix get_query_string method to handle empty query_string

---

src/oauth.cpp
test/test_oauth.cpp

Don't propagate exceptions during OAuth header parsing and validation. Instead, treat it as a validation failure.
Fixes #146.
@mmd-osm, could you try out this branch and let me know if it no longer crashes, please?

OAuth parsing failures should be failures, not crashes.

---

include/cgimap/backend/apidb/cache.hpp
include/cgimap/backend/apidb/changeset.hpp
src/backend/apidb/apidb.cpp
src/backend/apidb/changeset.cpp
src/backend/apidb/common_pgsql_selection.cpp
src/backend/apidb/readonly_pgsql_selection.cpp
src/backend/apidb/writeable_pgsql_selection.cpp

Fixes #122, and pretty much any other API call based on the same extraction logic.
I hope the general approach of tackling this issue is ok with only minor code cleanups needed.

[Perf] Mass prefetch user details for faster /map call

---

include/cgimap/api06/changeset_upload/osmchange_input_format.hpp
test/test_parse_osmchange_input.cpp

XML parser fixes after a round of fuzzing:
* Return HTTP 400 instead of 500 for invalid XML
* Removed XML_PARSE_RECOVER : the use of XML_PARSE_RECOVER in libxml2 is discouraged in production  code as it hides errors in invalid XML and exercises some less-tested code paths in libxml2.
Source: https://mail.gnome.org/archives/xml/2018-January/msg00016.html

Fix: XML parser handling for invalid data

---

include/cgimap/request.hpp
src/api06/map_handler.cpp
src/request.cpp

Fix confusing error message for /map call in case max node limit has been exceeded.
Previous behavior was a constant source of confusion to users, as most browsers would only display a meaningless error message, instead of telling the user that the bbox contains too many nodes.
This pull request introduces a change to only return the Content-Disposition header in case the overall request is successful (HTTP status code 200)
Old behavior:
New behavior:
References:
* https://help.openstreetmap.org/questions/45330/error-downloading-a-map-invalid-response
* https://help.openstreetmap.org/questions/67901/cant-export-maps-err_invalid_response
* https://help.openstreetmap.org/questions/50006/this-site-cant-be-reached-error-while-trying-to-export-a-map
* ... and many more ...

Fix confusing error message for /map call 

---

include/cgimap/backend/apidb/transaction_manager.hpp
src/backend/apidb/changeset_upload/node_updater.cpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
src/backend/apidb/transaction_manager.cpp

+ Fixes major performance issue with very large relations when determining added/removed relation members for bbox calculation
+ Added instrumentation code to log prepared statements execution times
See https://github.com/openstreetmap/operations/issues/236#issuecomment-467541630 for discussion

[perf] relation member changes for bbox calculation

---

src/backend/apidb/readonly_pgsql_selection.cpp
src/backend/apidb/writeable_pgsql_selection.cpp
test/test_apidb_backend_changesets.cpp

Prepared statement `extract_changesets` always fetches all related changeset comments from the _changeset_comments_ table, even though it hasn't been requested by the caller. Today, it's cgimap's job to discard that information in case it isn't needed.

[Perf] Avoid unnecessary changeset comment extraction, if not requested

---

include/cgimap/api06/changeset_upload/osmchange_tracking.hpp
include/cgimap/osm_diffresult_responder.hpp
include/cgimap/types.hpp
src/api06/changeset_upload/osmchange_tracking.cpp
src/api06/changeset_upload_handler.cpp
src/osm_diffresult_responder.cpp
test/test_apidb_backend_changeset_uploads.cpp

Improves code readability in osm_diffresult_responder.cpp by omitting irrelevant details from OSMChange_Tracking class.

Refactoring: improve OSMChange_Tracking diffresult isolation

---

src/basicauth.cpp

The cryptopp name is more portable - on Ubuntu it is a link to crypto++ and on Fedora it is the actual name of the directory and crypto++ doesn't work at all.

Use cryptopp path for crypto++ includes

---

src/backend/apidb/changeset_upload/node_updater.cpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp

If you don't name the columns explicitly then you are depending on the order of the columns in the database which may vary if the history of the database and how it was updated doesn't match the one you are developing against.

Specify columns explictly when inserting into API tables

---

src/backend/apidb/writeable_pgsql_selection.cpp

Write backend queries extract_historic-* were not explicitly sorted, resulting in non-sequential version numbers
Fixes #182

Sort History api call result by object and version

---

include/cgimap/backend/apidb/pgsql_update.hpp
include/cgimap/data_update.hpp
src/backend/apidb/apidb.cpp
src/backend/apidb/pgsql_update.cpp
src/process_request.cpp

See https://github.com/zerebubuth/openstreetmap-cgimap/issues/181#issuecomment-495989666:
A new command line parameter `--disable-write-api` allows disabling API write operations irrespective of the read only/write backend settings. 
Also, the description of the `--readonly` command line parameter has been rephrased to `use the read-only backend (default: write backend)`

Introduce --disable-api-write command line param to disable API writes

---

src/osm_current_responder.cpp
src/osm_diffresult_responder.cpp
src/osmchange_responder.cpp

Missing database user permissions were only sent to the client as `<error>` tag, leaving no information about such issue in the local log file. From an operations pov, this makes it next to impossible to detect and analyze such issues.
This pull request logs all exceptions during output, which catches database exceptions, but might also log issues about broken client connections. If this too noisy, a more fine granular logging based on exception type can be added in a subsequent PR. 
Fixes #180

Added exception logging in osm_responder subclasses

---

src/process_request.cpp

We need to use the same Realm as in the Rails API controller (https://github.com/openstreetmap/openstreetmap-website/blob/dbbbd62ef1982e905ceb23f1278e9b4bfdb49d5b/app/controllers/api_controller.rb#L6), because some clients are relying on the correct value.

Fix Basic Auth realm to be in sync with Rails

---

include/cgimap/backend/apidb/cache.hpp
src/backend/apidb/changeset.cpp
src/backend/apidb/readonly_pgsql_selection.cpp

Clean up some redundant code to fetch changeset metadata.

Simplify changeset cache sql

---

Makefile.am
include/cgimap/api06/changeset_upload/changeset_input_format.hpp
include/cgimap/api06/changeset_upload/osmchange_input_format.hpp
include/parsers/exception.h
include/parsers/internal_error.h
include/parsers/parse_error.h
include/parsers/parser.h
include/parsers/saxparser.h
include/parsers/wrapped_exception.h
src/Makefile.am
src/parsers/exception.cc
src/parsers/internal_error.cc
src/parsers/parse_error.cc
src/parsers/parser.cc
src/parsers/saxparser.cc
src/parsers/wrapped_exception.cc
src/process_request.cpp

- Lots of technical details when dealing with libxml are now hidden in a SAX parsing framework
- Better error handling
- No additional external dependencies. Small parts covering SAX parsing have been extracted from libxml++ and heavily adapted to cover the bare minimum required.
Closes #208

Migrate XML parsers to use SaxHandler

---

include/cgimap/http.hpp
src/http.cpp
test/test_parse_osmchange_input.cpp

Prepend HTTP 412 error text w/ Precondition failed: for Rails port compatibility

---

include/cgimap/options.hpp
src/main.cpp
src/options.cpp

Style guide recommends one to three words and no underscores.

Adapt new command line options to gnu style

---

Dockerfile
lighttpd.conf

* openstreetmap-cgimap binary now statically built
* Enable JSON output
* Multi-stage build for smaller image (1GB -> 120 MB)
* Run cgimap as non-root user (sec)
* Update lighttpd.conf to include all supported endpoints,
* Forward unknown requests to Rails port on  port 3000 (reverse proxy)
* Include config example for Dockerfile

Updated Dockerfile and lighttpd.conf

---

.travis.yml
Makefile.am
include/cgimap/api06/changeset_upload/way.hpp
include/cgimap/http.hpp
openstreetmap-cgimap.1
src/backend.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
src/main.cpp

References https://github.com/zerebubuth/openstreetmap-cgimap/issues/199
Refactored `environment_option_name` into a validation lambda that checks against the options in `po::options_description`.
Fixed up a few places in the code and Makefile where tabs and spaces didn't match and was causing visual alignment issues.
Updated `man` page to include config file description and oauth/update database command line arguments.

CGIMAP_* environment parameter blocks --help

---

src/oauth2.cpp
test/test_apidb_backend_oauth2.cpp
test/test_oauth2.cpp

Post 0.8.4-release changes in Rails port doorkeeper settings caused some incompatible changes on the db side.
Related:
* Rails port change: https://github.com/openstreetmap/openstreetmap-website/commit/e9010306c5b4970edf5cb8164feb43719d3bb63a
* Discussion: https://github.com/zerebubuth/openstreetmap-cgimap/pull/246#issuecomment-867968706

OAuth2: plain token support

---

include/cgimap/backend/apidb/utils.hpp
include/cgimap/data_selection.hpp
include/cgimap/util.hpp
src/backend/apidb/changeset_upload/node_updater.cpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
src/backend/apidb/common_pgsql_selection.cpp
src/data_selection.cpp
test/test_apidb_backend_nodes.cpp

Fixes https://github.com/zerebubuth/openstreetmap-cgimap/issues/276
Reverts https://github.com/zerebubuth/openstreetmap-cgimap/pull/261
libpqxx seems to treat semicolons as a separator character regardless of the actual field type (Postgresql docs mention that only box type uses semicolon, all other standard types use comma only).
As our payload in varchar fields may contain semicolons, the array_agg() result would throw off the libpqxx array parser.
So for now we revert to the previous custom parser implementation.
Further upstream issue analysis to follow.

Undo "Replace custom array parser by pqxx::array_parser"

---

include/cgimap/infix_ostream_iterator.hpp

The [std::iterator](https://en.cppreference.com/w/cpp/iterator/iterator) helper class has been deprecated in C++ 17 in favor of direct declaration of the iterator member types. This causes the compiler to emit a ton of deprecation warnings, once for every source file that somehow includes the affected `infix_ostream_iterator.hpp` header.
* Fixed deprecation warnings by directly declaring the required member types and no longer deriving from std::iterator.
* `difference_type` changed to `std::ptrdiff_t` instead of `void` for [C++ 20 compatibility](https://en.cppreference.com/w/cpp/iterator/ostream_iterator).
* Add `iterator_concept` member type for [C++ 20 compatibility](https://en.cppreference.com/w/cpp/iterator/iterator_tags)

Replace deprecated std::iterator with direct member type declarations

---

include/cgimap/backend/apidb/readonly_pgsql_selection.hpp
include/cgimap/data_selection.hpp
src/backend/apidb/readonly_pgsql_selection.cpp
src/backend/staticxml/staticxml.cpp
src/process_request.cpp
test/test_apidb_backend_changeset_uploads.cpp
test/test_apidb_backend_oauth.cpp
test/test_apidb_backend_oauth2.cpp
test/test_basicauth.cpp

Check user state, only allow db changes for confirmed and active users

---

include/cgimap/http.hpp
include/cgimap/rate_limiter.hpp
src/http.cpp
src/options.cpp
src/process_request.cpp
src/rate_limiter.cpp
test/test_apidb_backend_oauth.cpp
test/test_apidb_backend_oauth2.cpp

Let me know how ugly solution it is from 0 to 10 to do `if (e.code() == 509)` and then `dynamic_cast`. It shows that my language is C# :P

Fix #291: Add Retry-After http header in 509 response

---

include/cgimap/backend/apidb/pgsql_update.hpp
include/cgimap/data_update.hpp
include/cgimap/http.hpp
include/cgimap/options.hpp
src/api06/changeset_upload_handler.cpp
src/backend/apidb/pgsql_update.cpp
src/http.cpp
src/main.cpp
src/options.cpp
test/test_apidb_backend_changeset_uploads.cpp

See https://github.com/openstreetmap/openstreetmap-website/pull/4319 for details
* Introduces a new parameter `--ratelimit-upload` to rate limit changeset uploads
* Check is done using a Postgresql plpgsql database function `api_rate_limit`, which accepts a user id as input parameter, and returns the number of permitted database changes for this user.
* Details of this database function are out of scope for CGImap. The respective implementation can be found in https://github.com/openstreetmap/openstreetmap-website -> lib/database_functions.rb
* The database function MUST be deployed before enabling upload rate limiting on CGImap, otherwise the upload will fail with HTTP 500 Internal Server Error.
* Once rate limiting has been enabled, the log file should show entries like  `Executed …

Added changeset upload rate limiting

---

src/request_helpers.cpp

Status is a non-standard http header field, but we should show the right text for http 429.

Adding right text for HTTP "Status" field 

---

Makefile.am
src/Makefile.am
test/test_parse_options.cpp

Code coverage thinks we could do some more unit tests here.

Added test case for command line options parsing

---

Dockerfile
Dockerfile2204
Dockerfile_bookworm
Dockerfile_trixie
src/main.cpp

List of changes:
* Show warning when ` --instances` command line parameter is set when in non-daemon mode
* Dockerfiles: To facilitate monitoring, logfiles are now sent to the Docker daemon's stdout, and are accessible using `docker logs -f ...` . Also, Dockerfiles are starting CGImap in daemon mode, to automatically restart forked CGImap processes. The container stops, if the main CGImap process terminates, or docker stop is invoked on the container.
* Dockerfile: Default number of instances in daemon mode is now 10 instead of 30.
* Some refactoring into non-daemon/daemon mode
Fixes #330

Daemon mode

---

Makefile.am
configure.ac

This at least allows it to run again. The `.clang-format` style file produces some suboptimal results and should be updated.

Update make clang-format target

---

src/main.cpp

Forked process restarts (due to some exceptions) are now limited to max 1/s, to avoid excessive restarts. Also, database exception details are now written to the log file.

Daemon mode: rate limit process restarts in case of exceptions

---

src/main.cpp

https://eel.is/c++draft/support.signal
A simple boolean will almost always work in practice, but technically it's not thread/signal safe and behavior depends on the compiler and architecture.

Make signal flags atomic for explicit signal safety

---

src/main.cpp

See https://github.com/zerebubuth/openstreetmap-cgimap/pull/336#issuecomment-1848958961 
Commit message should be really "defaulted value" rather  "default value". A warning is also shown when adding `--instances=5`, even though 5 is the default value.
Also moved some static functions in main.cpp to an anonymous namespace and removed "static".

Fix program option --instances

---

include/cgimap/output_formatter.hpp
include/cgimap/util.hpp
include/cgimap/xml_writer.hpp
src/json_formatter.cpp
src/xml_formatter.cpp
src/xml_writer.cpp

- Use std::to_chars to convert integers to strings for xml serialization instead of xml attribute string formatter 
- No temporary heap allocations
- At _least_ 4 temporary heap allocations per element eliminated (element id, element version, changeset number, last user id)
- std::to_chars is generally the fastest string conversion function available
- Add char* overloads for xml_writer functions to avoid temporary std::string allocations
- Passing string literals to a const std::string& parameter requires a temporary std::string object. (libxml2 only uses char* anyway.)
- Deduplicate and move common string constants to base formatter class

Reduce temporary allocations for xml serialization

---

include/cgimap/backend/apidb/oauth_store.hpp
include/cgimap/backend/apidb/readonly_pgsql_selection.hpp
include/cgimap/backend/staticxml/staticxml.hpp
include/cgimap/data_selection.hpp
include/cgimap/oauth.hpp
include/cgimap/oauth2.hpp
include/cgimap/process_request.hpp
src/backend/apidb/oauth_store.cpp
src/backend/apidb/readonly_pgsql_selection.cpp
src/backend/staticxml/staticxml.cpp
src/oauth2.cpp
src/process_request.cpp
test/redactions.testcore/oauth.json
test/redactions.testcore/roles.json
test/test_apidb_backend_changeset_uploads.cpp
test/test_apidb_backend_changesets.cpp
test/test_apidb_backend_oauth.cpp
test/test_apidb_backend_oauth2.cpp
test/test_basicauth.cpp
test/test_core.cpp
test/test_oauth.cpp
test/test_oauth2.cpp

As a preparation step for OAuth 1.0a removal, the following two methods were moved to the data_selection class. The oauth::store class (and related OAuth 1.0a classes) will be removed in a later commit.
* get_roles_for_user
* get_user_id_for_oauth2_token
Also, oauth.json in redactions.testcore was split up in two files, with roles.json listing all user roles.

Relocate two methods to data_selection class

---

src/json_writer.cpp
test/json.testcore/data.osm
test/json.testcore/regression_double_truncated.case

Fixes https://github.com/zerebubuth/openstreetmap-cgimap/issues/363
The json formatter used a 12 byte buffer to format floating point values. This is not enough to hold the full string including the final null terminator byte for negative values with three digits before the decimal point and seven digits precision. The output of `snprintf()` was not checked, so if there is a digit which does not fit into the buffer it will be silently dropped.
E.g.  `-117.0671669` has 12 digits/bytes including the minus sign character. However, the terminating null character also requires 1 byte so the output string gets silently truncated to `-117.067166`.
This means that all coordinates with longitudes from -100 to -180, which is mostly the western USA and Canada, will be shifted by up to ~11cm at the …

Fix json output incorrectly truncating coordinates 

---

CMakeLists.txt
contrib/CMakeLists.txt
contrib/catch2/CMakeLists.txt
contrib/libxml++/CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt

Move contrib libs cmake definitions out of main cgimap cmake files into separate CMakeLists.txt files per library

Create separate cmake files for contrib libs

---

test/CMakeLists.txt

The node.testcore test was accidentally defined twice, once individually and once along with all other *.testcore tests.
(Leftover definition that was used for testing when cmake was added)

Remove duplicated cmake test definition

---

CMakeLists.txt

This was missing in 53b7d3f10fec255e04a7bf52e8e68cbd7200d963 where YAJL v1 code has been removed already.

Require YAJL v2 in CMakeLists

---

CMakeLists.txt
README
cmake/FindBrotli.cmake
docker/debian/Dockerfile_bookworm
docker/debian/Dockerfile_trixie
docker/ubuntu/Dockerfile
docker/ubuntu/Dockerfile2204
include/cgimap/brotli.hpp
include/cgimap/http.hpp
src/CMakeLists.txt
src/brotli.cpp
src/http.cpp
test/test_http.cpp

* Brotli enabled by default in CMakeLists (is this a good idea?)
* Adds a new package dependency: libbrotli-dev
* Compression level 5 seems to be a good trade-off between compression rate and processing time.
* Brotli is the preferred option for `Accept-Encoding: gzip, compress, br` http header, like on the Rails port/mod_brotli on Apache.
* Changeset upload decompression is not in scope, maybe we could add this later.
---
Implementation details:
* cmake/FindBrotli.cmake was copied over from https://github.com/yhirose/cpp-httplib/blob/master/cmake/FindBrotli.cmake. It seemed like one of the more complete implementations that I could find out there.
* Brotli API calls in src/brotli.cpp were based on the implementation in https://github.com/yhirose/cpp-httplib/blob/master/httplib.h 
--- …

Added support for brotli response body compression

---

include/cgimap/brotli.hpp
include/cgimap/json_writer.hpp
include/cgimap/output_buffer.hpp
include/cgimap/zlib.hpp
src/brotli.cpp
src/fcgi_request.cpp
src/json_writer.cpp
src/request_helpers.cpp
src/zlib.cpp
test/test_request.cpp
test/test_request.hpp

Previously, `wrap_write` function was called frequently for small amounts of data. This resulted in FCGX_PutStr or some compression function showing up at the top of the perf trace. With this change in place, we're leveraging the YAJL internal buffer, and only output data once a certain threshold value is reached.

yajl: output json in larger chunks

---

src/backend/apidb/common_pgsql_selection.cpp
src/backend/apidb/readonly_pgsql_selection.cpp
test/test_apidb_backend_changesets.cpp

From libpqxx docs:
> pqxx::field pqxx::row::at (const char f[]) const
> Warning: This is much slower than indexing by number, or iterating.
Without caching, we're repeatedly calling PQfnumber for each row/field, which does a strcmp across all column names. Since our queries don't return a huge number of columns, this was not too bad before.

libpqxx: cache column names

---

.clang-tidy
.iwyu_mappings.imp
CMakeLists.txt
cmake/BuildLint.cmake
contrib/CMakeLists.txt

Add option to automatically run clang-tidy during compilation. Currently disabled by default due to the number of warnings it produces. The enabled checks can be configured in `.clang-tidy`.
Also adds some more options for other linters that are directly supported by cmake.

Integrate clang-tidy in cmake build

---

include/cgimap/output_formatter.hpp
src/backend/apidb/common_pgsql_selection.cpp
src/output_formatter.cpp

Follow up for https://github.com/zerebubuth/openstreetmap-cgimap/pull/344#issuecomment-2043634749

Some cleanups from @Woazboat psql-array-iterator branch

---

src/backend.cpp
src/mime_types.cpp
src/oauth2.cpp

\+ some whitespace / parentheses cleanup

Use raw string literal for bearer token regex

---

src/backend/apidb/common_pgsql_selection.cpp
src/backend/apidb/readonly_pgsql_selection.cpp
test/test_apidb_backend_changesets.cpp

As of today, changeset comments were discarded only at the time of generating the XML/JSON output. That's slightly wasteful. Instead, we now pass the `include_changeset_discussions` flag to the changeset extraction SQL statement to stop extra effort as early as possible.

Skip changeset discussions unless requested

---

include/cgimap/backend/apidb/common_pgsql_selection.hpp
src/backend/apidb/common_pgsql_selection.cpp

This adds a small wrapper function to take advantage of pqxx::field size information, so  `.c_str()` will no longer be needed everywhere. Some test code still requires the std::string_view variant to be around.

pqxx::field wrapper for psql_array_to_vector

---

CMakeLists.txt
openstreetmap-cgimap.1
src/backend.cpp
src/backend/apidb/CMakeLists.txt
src/main.cpp
test/CMakeLists.txt

This PR addresses the two remaining topics from #368, namely removing multi-backend support, and removing the ENABLE_APIDB compile time flag. With the staticxml backend removal in 0.9.1, there's not much point in keeping this code around for a single remaining APIDB backend.
*/CMakeLists.txt need a bit of reformatting which will be done later.
Closes #368

Remove multi-backend support

---

contrib/CMakeLists.txt

Linking the libxml++ contrib library with cgimap_common_compiler_options with INTERFACE scope is a bug as that only applies to targets using the library but not the library itself.
(Copy paste error from catch2 which is a header only interface library and can therefore only link to other libraries with INTERFACE scope)
https://github.com/zerebubuth/openstreetmap-cgimap/commit/0901120a963542b457ceb1f45890e18de4b4be88#diff-f3c6529ba39f2f8fe71ba721bdb3eccec46bd4ba024980398b12c7e7cd3f2672R5

Fix libxml++ contrib library compiler options

---

.github/workflows/docker_2404.yml
docker/ubuntu/Dockerfile2404
src/main.cpp

See discussion in https://github.com/openstreetmap/operations/issues/999
Test build on Ubuntu Launchpad: https://launchpad.net/~mmd-osm/+archive/ubuntu/090d4085-d853-46f6-a62a-9d78db954ac9/+packages

Add build on Ubuntu 24.04

---

include/cgimap/api06/changeset_upload/changeset_updater.hpp
include/cgimap/backend/apidb/changeset_upload/changeset_updater.hpp
include/cgimap/backend/apidb/pgsql_update.hpp
include/cgimap/data_update.hpp
include/cgimap/options.hpp
include/cgimap/util.hpp
src/api06/changeset_upload_handler.cpp
src/backend/apidb/changeset_upload/changeset_updater.cpp
src/backend/apidb/pgsql_update.cpp
src/main.cpp
src/options.cpp
test/test_apidb_backend_changeset_uploads.cpp

See #412 for details.
For reviewers out there, please add inline comments as needed. Thanks!
Introduces a new config option: `bbox-size-limit-upload`  (boolean value)

Add the ability to limit changeset size

---

include/cgimap/api06/changeset_close_handler.hpp
include/cgimap/api06/changeset_create_handler.hpp
include/cgimap/api06/changeset_update_handler.hpp
include/cgimap/api06/changeset_upload_handler.hpp
include/cgimap/backend/apidb/changeset_upload/changeset_updater.hpp
include/cgimap/backend/apidb/changeset_upload/node_updater.hpp
include/cgimap/backend/apidb/changeset_upload/relation_updater.hpp
include/cgimap/backend/apidb/changeset_upload/way_updater.hpp
include/cgimap/backend/apidb/pgsql_update.hpp
include/cgimap/data_update.hpp
include/cgimap/handler.hpp
include/cgimap/request_context.hpp
include/cgimap/request_helpers.hpp
src/api06/changeset_close_handler.cpp
src/api06/changeset_create_handler.cpp
src/api06/changeset_update_handler.cpp
src/api06/changeset_upload_handler.cpp
src/backend/apidb/changeset_upload/changeset_updater.cpp
src/backend/apidb/changeset_upload/node_updater.cpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
src/backend/apidb/pgsql_update.cpp
src/process_request.cpp
test/test_apidb_backend_changeset_uploads.cpp

Make context information about the request (user id, roles, ...) available in change handlers.
Unblocks future features like https://github.com/zerebubuth/openstreetmap-cgimap/pull/409#issuecomment-2171787640

Propagate request context to handlers

---

include/cgimap/backend/apidb/changeset_upload/relation_updater.hpp
include/cgimap/handler.hpp
include/cgimap/mime_types.hpp
include/cgimap/request_context.hpp
src/api06/changeset_upload_handler.cpp
src/backend/apidb/changeset_upload/changeset_updater.cpp
src/backend/apidb/changeset_upload/node_updater.cpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
src/backend/apidb/common_pgsql_selection.cpp
src/backend/apidb/quad_tile.cpp
src/choose_formatter.cpp
src/fcgi_request.cpp
src/http.cpp
src/json_writer.cpp
src/logger.cpp
src/main.cpp
src/mime_types.cpp
src/osmchange_responder.cpp
src/process_request.cpp
src/request_helpers.cpp
src/router.cpp
src/routes.cpp
test/test_apidb_backend_changeset_uploads.cpp

* Split ApiDB_Relation_Updater::lock_future_members into smaller methods
* RequestContext: removed start_time again, this info is also available as req.get_current_time()
* Changed `(*req_ctx.user).id`  to `req_ctx.user->id` for better readability
* validate_user_db_update_permission: use RequestContext instead of request
* Switch back to request instead of RequestContext for non POST/PUT methods
* Some linter fixes

Small refactorings

---

include/cgimap/rate_limiter.hpp
src/rate_limiter.cpp

memcached entries were previously created without expiration. Since we know at which point in time these entries become irrelevant, we can restrict the lifetime accordingly.

memcached: add non-zero expiration value

---

include/cgimap/rate_limiter.hpp
src/rate_limiter.cpp
test/test_apidb_backend_oauth2.cpp

In extreme cases, the memcached entry was dropped too early (first download larger than maxdebt limit).

rate_limiter-update: consumed bytes may be larger than maxdebt

---

include/cgimap/api06/changeset_upload/changeset_input_format.hpp
include/cgimap/api06/changeset_upload/node.hpp
include/cgimap/api06/changeset_upload/osmchange_xml_input_format.hpp
include/cgimap/api06/changeset_upload/osmobject.hpp
include/cgimap/api06/changeset_upload/relation.hpp
include/cgimap/api06/changeset_upload/way.hpp
src/api06/changeset_upload_handler.cpp
test/CMakeLists.txt
test/test_apidb_backend_changeset_uploads.cpp
test/test_parse_osmchange_xml_input.cpp

This PR includes some upfront refactoring, which was originally part of #407, but really unrelated to JSON format.
Note: the second commit has a typo, it should read "Rename osmchange_input_format → osmchange_xml_input_format"

Some refactorings for "JSON support for changeset upload"

---

src/http.cpp
src/oauth2.cpp
test/test_apidb_backend_oauth2.cpp
test/test_http.cpp
test/test_oauth2.cpp

Replace std::regex by simpler parsing alternatives

Simplify std::regex

---

include/cgimap/util.hpp

Reverts changes in a10d1f2a0b155ebab93234629278d7a80b3b971b

Header file should use inline instead of anonymous namespace

---

CMakeLists.txt
contrib/CMakeLists.txt
contrib/libxml++/CMakeLists.txt
src/CMakeLists.txt

* Use implicit default values where possible
* Simplify cmake install targets via GNUInstallDirs module
* Installation directories for binaries, libaries, etc... are set automatically according to their target type
* Define components for install/package targets
* Allows building separate packages for binaries and development headers (`*-dev` package)
* Rename included modified libxml++ to differentiate it from original libxml++

Refactor cmake install and package definitions

---

.github/workflows/docker_bookworm.yml
docker/debian/Dockerfile_bookworm
docker/debian/Dockerfile_trixie
docker/ubuntu/Dockerfile2204
docker/ubuntu/Dockerfile2404

This PR is based on work by @Woazboat  in d499553211747d8df75cd6647d04769e03aa0c89, with some minor tweaks to upload the generated Debian build artifacts later on. Also, Debian 12 Dockerfile has additional compile flags similar to Ubuntu launchpad config.

Debian package build

---

include/cgimap/backend/apidb/pqxx_string_traits.hpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp

Without "inline", clang 17 was rightfully complaining about multiple definitions of `pqxx::type_name<... >'

Adjustments for libpqxx-7.x, clang, macOS

---

.github/workflows/macos_14.yml
contrib/sjparser/library/CMakeLists.txt
include/cgimap/api06/changeset_upload/node.hpp
include/cgimap/backend/apidb/pqxx_string_traits.hpp
include/cgimap/util.hpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
src/backend/apidb/pgsql_update.cpp
src/fcgi_request.cpp
src/main.cpp
src/request.cpp

MacOS issues reported in #455

---

src/process_request.cpp

Skip rate limiting check in case of HTTP OPTIONS since it interferes with CORS preflight requests
See https://github.com/facebook/Rapid/issues/1424 for context

Don't rate limit HTTP OPTIONS requests

---

include/cgimap/backend/apidb/common_pgsql_selection.hpp
include/cgimap/backend/apidb/utils.hpp
src/backend/apidb/common_pgsql_selection.cpp
src/backend/apidb/utils.cpp
test/test_apidb_backend_nodes.cpp

* `psql_array_ids_to_vector` consolidates multiple calls of `std::from_chars` in a single place
- Similar to psql_array_to_vector
- No escaping & creating temp strings needed
- A bit of a follow up for #344
Some further smaller changes  in this PR:
* `extra_info` instances are initialized in constructor instead of a separate extract method
* `psql_array_to_vector` has a new size hint parameter to avoid reallocations
*  `emplace_back` for in place vector creation
* Move helper functions to util.[ch]pp

Introduce psql_array_ids_to_vector

---

include/cgimap/backend/apidb/changeset_upload/node_updater.hpp
include/cgimap/backend/apidb/changeset_upload/relation_updater.hpp
include/cgimap/backend/apidb/changeset_upload/way_updater.hpp
src/backend/apidb/changeset_upload/node_updater.cpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
src/backend/apidb/pgsql_update.cpp

This PR removes the need for temporary tables during diff upload by leveraging CTE. As a result, copying new objects from temporary to current tables, and cleaning up temporary tables afterwards is no longer required.

Diff upload: CTE instead of temporary tables

---

.github/workflows/alpine.yml
contrib/sjparser/library/sjparser/internals/token_parser.h
docker/alpine/Dockerfile_alpine
src/time.cpp

Alpine based docker image takes about 25MB instead of 135MB.

Add alpine based Dockerfile

---

include/cgimap/backend/apidb/utils.hpp
src/backend/apidb/changeset_upload/changeset_updater.cpp
src/backend/apidb/changeset_upload/node_updater.cpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
src/backend/apidb/readonly_pgsql_selection.cpp

This PR standardizes SQL statements to use C++ raw string literals for easier maintenance. Additionally, we use a C++20 string literal operator named `_M` to remove indentation at compile time, resulting in a format nearly identical to the previous one.
https://godbolt.org/z/5je94K4ve illustrates the compile time step.
GCC 11 and older lack full support for the unindent step, so the original string is used instead.

SQL statements as raw string, store as unindented string

---

include/cgimap/options.hpp
src/http.cpp
src/options.cpp

This PR removes the last remaining std::regex. It was taking care of postgresql timeout intervals for two command line parameters. The replacement is based on c++20 ranges.

options.cpp: replace interval regex by simple parser

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

I added this VS Code devcontainer to make it a bit easier for new folks to get started (and for me to have an environment similar to production). At least building binaries and running test cases seems to work fine at the moment. Of course, additional tools can be added if it makes sense.

VS Code devcontainer added

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.vscode/cmake-variants.yaml

Added cmake build configs for coverage, added extension to display coverage info
CMake now comes with a few new predefined build variants, including coverage support.
After running ctest, coverage files need to be imported:
"Gcov Viewer: Show" enhances the editor view with coverage details:

Added more tools to devcontainer

---

include/cgimap/backend/apidb/common_pgsql_selection.hpp
src/backend/apidb/common_pgsql_selection.cpp
src/backend/apidb/readonly_pgsql_selection.cpp
test/CMakeLists.txt
test/json.testcore/data.osm
test/json.testcore/regression_double_truncated.case
test/node.testcore/data.osm
test/node.testcore/node_2.case
test/node.testcore/nodes.case
test/node.testcore/nodes_dup2.case
test/relation.testcore/data.osm
test/relation.testcore/relation_1.case
test/relation.testcore/relations.case
test/relation_full.testcore/data.osm
test/relation_full.testcore/relation_1.case
test/relation_full.testcore/relation_4.case
test/staticxml.cpp
test/test_apidb_backend_core.cpp
test/test_apidb_importer.cpp
test/test_apidb_importer.hpp
test/test_core.cpp
test/test_database.cpp
test/test_database.hpp
test/way_full.testcore/data.osm
test/way_full.testcore/way_1.case
test/xmlparser.cpp
test/xmlparser.hpp

Like test_core, but serving data from real database.
Addresses issue in #487
* Tags are now sorted (previously, the order was undefined, resulting in sporadic test failures). Some test cases had to be fixed due to this change. staticxml serves tags in the exact sequence as in data.osm, tags are stored in a vector and are not sorted afterwards.
* Sorting has been fixed for mixed current/historic scenarios, like api/0.6/nodes?nodes=3v1,3 
* Continued catch2 migration, execute each unit test file as dedicated SECTION to execute as many tests as possible, even if one of them fails.
* Lambda callback function in readonly_pgsql has been removed, because it is no longer needed now.
* Removed two obsolete run* functions in test_database.[ch]pp.
* get_user_id_for_oauth2_token would fail if the …

test_apidb_backend_core - test_core w/ db support

---

.vscode/cmake-variants.yaml
CMakeLists.txt
src/osmchange_responder.cpp
src/text_formatter.cpp
test/test_formatter.cpp

This PR adds a cmake target to generate an html based code coverage report,  something like:
`ninja generate_coverage_report` (or `make` instead of `ninja`).
coveralls.io: https://coveralls.io/github/zerebubuth/openstreetmap-cgimap

Added cmake target for code coverage reports

---

doc/man1/openstreetmap-cgimap.1
src/backend/apidb/apidb.cpp
src/backend/apidb/pgsql_update.cpp
src/backend/apidb/readonly_pgsql_selection.cpp

* Remove changeset size parameter, changeset cache was removed many years ago
* Remove option to override character set, always assume default "utf8"

Remove obsolete config options

---

include/cgimap/http.hpp
src/http.cpp

Enables reuse of const char* constructor, avoids unnecessary std::string construction

Derive http::exception from std::runtime_error

---

src/options.cpp
test/test_parse_options.cpp

50k changes per changeset was the biggest number ever in place. We don't want people to go for even bigger values, because of performance concerns. These days, 10k is the default value.
Context: https://github.com/developmentseed/osm-seed/pull/300#issuecomment-2817089990

Limit max-changeset-elements to 50'000 changes

---

src/main.cpp
src/process_request.cpp

Low level exceptions, like database errors, should be sent to clients as an Internal Server Error.
To reproduce:
Session 1:
---------------
Start cgimap on an empty database instance:
```bash
pg_virtualenv
./openstreetmap-cgimap --dbname=postgres --socket .demo
```
Session 2:
---------------
Try to issue a request:
```bash
REQUEST_URI="/api/0.6/node/1" REQUEST_METHOD="GET" REMOTE_ADDR="127.0.0.1" cgi-fcgi -bind -connect .demo
```
Should return:
```
Status: 500 Internal Server Error
Content-Type: text/plain
Content-Length: 129
Error: ERROR:  relation "current_nodes" does not exist LINE 1: SELECT id FROM current_nodes WHERE id = ANY($1)                        ^
Cache-Control: no-cache
ERROR:  relation "current_nodes" does not exist
LINE 1: SELECT id FROM current_nodes WHERE id = ANY($1)
```

Finish up FCGI request in case of exceptions

---

src/backend/apidb/changeset_upload/relation_updater.cpp
test/test_apidb_backend_changeset_uploads.cpp

Code review finding. Sequence ids are used for sorting purposes only and not shared with any API clients. They should start with 1, like on Rails. Old relation member sequence ids can stay as is for now.

Relation member sequence ids should start with 1

---

include/cgimap/api06/changeset_upload/node.hpp
include/cgimap/api06/changeset_upload/osmchange_xml_input_format.hpp
include/cgimap/api06/changeset_upload/osmobject.hpp
include/cgimap/api06/changeset_upload/relation.hpp
include/cgimap/api06/changeset_upload/way.hpp
src/backend/apidb/changeset_upload/node_updater.cpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
test/test_apidb_backend_changeset_uploads.cpp
test/test_parse_osmchange_xml_input.cpp

Since Mid-2019 and up to v2.0.1, positive placeholder ids in "`<create>` operations" were triggering an HTTP 404 error as a side effect of a failing `lock_current_*` method call. Essentially, they were never supported by this implementation.
With the introduction of https://github.com/zerebubuth/openstreetmap-cgimap/commit/9505125892d88156b19a80b55de9140f12800ebf, `save_current_*_to_history` was triggering an HTTP 500 instead.
This PR adds an explicit check for negative placeholder ids during create, and rejects non-compliant requests with HTTP 400 "Placeholder IDs must be negative for created elements".
---
<details>
<summary>Comparison to Rails</summary>
NB: On Rails, positive placeholder ids are not rejected. However, the newly created objects cannot be referenced by their positive …

Placeholder ids must be negative for create ops

---

include/cgimap/api06/changeset_upload/node_updater.hpp
include/cgimap/backend/apidb/changeset_upload/node_updater.hpp
include/cgimap/brotli.hpp
include/cgimap/logger.hpp
include/cgimap/output_buffer.hpp
include/cgimap/request.hpp
include/cgimap/zlib.hpp
src/backend/apidb/changeset_upload/node_updater.cpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
src/brotli.cpp
src/fcgi_request.cpp
src/json_writer.cpp
src/logger.cpp
src/process_request.cpp
src/request.cpp
src/request_helpers.cpp
src/xml_writer.cpp
src/zlib.cpp
test/test_empty_selection.hpp
test/test_request.cpp
test/test_request.hpp

Summary of changes:
* Set own handler via `xmlSetGenericErrorFunc` in xml_writer.cpp, instead of implicitly reusing stale xmlpp defined handler. This is relevant for POST/PUT endpoints which process user provided XML files, and respond with an XML message. The xmlpp handler would be used, in case output_buffer methods fail.
* All output_buffer methods are now noexcept, since they're calling C libraries (FCGI, brotli, zlib) only, which don't throw. We are returning  -1  in case of error now instead of throwing exceptions.
*  `wrap_write` and `wrap_close` functions were previously potentially throwing exceptions, which is not permitted in the context of C callback functions (UB). This issue seems to be around since 2011 or so.
* Fixes for CppCoreGuidelines _C.138: Create an overload set for …

output_buffer: error handling w/o exceptions

---

include/cgimap/api06/changeset_upload/changeset_stats.hpp
include/cgimap/api06/changeset_upload/changeset_updater.hpp
include/cgimap/api06/changeset_upload/node_updater.hpp
include/cgimap/api06/changeset_upload/osmchange_handler.hpp
include/cgimap/api06/changeset_upload/relation_updater.hpp
include/cgimap/api06/changeset_upload/way_updater.hpp
include/cgimap/backend/apidb/changeset_upload/changeset_updater.hpp
include/cgimap/backend/apidb/changeset_upload/node_updater.hpp
include/cgimap/backend/apidb/changeset_upload/relation_updater.hpp
include/cgimap/backend/apidb/changeset_upload/way_updater.hpp
include/cgimap/options.hpp
src/api06/changeset_upload/osmchange_handler.cpp
src/api06/changeset_upload_handler.cpp
src/backend/apidb/changeset_upload/changeset_updater.cpp
src/backend/apidb/changeset_upload/node_updater.cpp
src/backend/apidb/changeset_upload/relation_updater.cpp
src/backend/apidb/changeset_upload/way_updater.cpp
src/main.cpp
src/options.cpp
test/structure.sql
test/test_apidb_backend_changeset_uploads.cpp
test/test_apidb_importer.cpp

https://github.com/openstreetmap/openstreetmap-website/issues/5758
[#6170](https://github.com/openstreetmap/openstreetmap-website/pull/6170)
Introduces new config option:
```
--changeset-enhanced-stats arg  enable enhanced changeset stats
```
This should translate to `CGIMAP_CHANGESET_ENHANCED_STATS=true` as environment variable.

Enhanced changeset statistics
